services:
  - type: web
    name: pharmacy-backend
    env: python
    plan: free
    rootDir: pharmacy_project
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && gunicorn pharmacy_project.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: pharmacy-backend-jhju.onrender.com
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://pharmacy-backend-jhju.onrender.com,https://pharmacy-management-system-zeta.vercel.app
      - key: DJANGO_CORS_ALLOW_ALL
        value: False
      - key: DJANGO_CORS_ALLOWED_ORIGINS
        value: https://pharmacy-management-system-zeta.vercel.app
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_SDMbCqf74Xel@ep-mute-tooth-aihg97zc-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
